### ISSUE TITLE
有一种相似的思路，但是另一种实现方式。可以看看有没有参考价值

### ISSUE THREAD

**Issue by looa** [AlanCheen/Flap#9]
https://github.com/looa/RecyclerKit
一个依赖注入框架。

**Comment by AlanCheen** [comment]
你好 注解的实现方式确实是我后续考虑的方向，暂时还没尝试，想先按照当前的思路做到1.0.0再尝试注解。

感谢分享，到时候多多指教。

**Comment by looa** [comment]
多交流（咱俩有微信），上面的框架还是0.0.1版本，功能还比较薄弱，只是一个基础的控制反转的实现

**Comment by AlanCheen** [comment]
好的，微信上你是哪个？ 发我一条消息。
